---

- hosts: webservers
  vars_files: {{ env }}/group_vars/all.yml

  roles:
    - common
    - nginx

- hosts: database
  vars:
    postgresql_objects_users:
    - name: dbadmin
      password: password
      role_attr_flags: SUPERUSER
      state: present
    postgresql_objects_databases:
    - name: dbadmin
      owner: dbadmin
      state: present
    postgresql_objects_become: true
    postgresql_objects_become_user: postgres

  roles:
    - role: postgres
    - role: postgresql_objects


- hosts: loadbalancer

  roles:
    - { role: common, when: "env == 'prod'" }
    - { role: haproxy, when: "env == 'prod'" }
