---

ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
ansible_user: ubuntu
env: prod
server1_ip: 10.0.5.153
server2_ip: 10.0.5.222
db_ip: 10.0.5.152
webserver_subnet: 10.0.5.0/24
db_password: "{{ vault_db_password }}"
lb_algo: roundrobin
db_user: dbadmin
db_name: dbadmin
