---

- name: help x2
  debug:
  msg: "{{ansible_user}}"
  become: true

- name: help
  command: echo $LOGNAME
  become: true
  register: output

- name: help x3
  debug: output.stdout



- name: update apt
  apt:
    update_cache: yes
  become: true
  become_user: root

- name: upgrade apt
  apt:
    upgrade: yes
  become: true
  become_user: root
