---

- name: edit pg_hba to allow webservers to authenticate
  template:
    src: templates/dev_pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
  when: env == "dev"
  become: true
  register: pg_hba

- name: edit pg_hba to allow webservers to authenticate
  template:
    src: templates/prod_pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
  when: env == "prod"
  become: true
  register: pg_hba

- name: restart_postgres straight away
  service:
    name: postgresql
    state: restarted
  become: true
  when: pg_hba.changed

- name: copy over psql script
  copy:
    src: files/compliments.psql
    dest: /home/ubuntu/compliments.psql

- name: checking if database table exists
  shell: "psql -U {{ db_user }} -d {{ db_name }}  -lqTa | grep compliments"
  register: table_exists

- name: add table and data if it doesn't exist
  command: "psql -U {{db_user }} -d {{ db_ name }} -f compliments.psql"
  when: table_exists.rc != 1
