---
- name: add postgres repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
    state: present
  become: true

- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: install postgres 9.5, postgres-php module and pyscopg2
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: true
  with_items:
    - postgresql-9.5
    - php5-pgsql
    - python-psycopg2

- name: edit config file so postgres listens all all ips
  copy:
    src: files/postgresql.conf
    dest: /etc/postgresql/9.5/main/postgresql.conf
  become: true
  register: postgresconf

- name: edit pg_hba to allow webservers to authenticate
  template:
    src: templates/dev_pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
  when: env == "dev"
  become: true
  register: pg_hba

- name: edit pg_hba to allow webservers to authenticate
  template:
    src: templates/prod_pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
  when: env == "prod"
  become: true
  register: pg_hba

- name: restart_postgres straight away
  service:
    name: postgresql
    state: restarted
  become: true
  when: pg_hba.changed or postgresconf.changed
