---

ansible_ssh_private_key_file: ~/.ssh/ANNA.pem
ansible_user: ubuntu
env: dev
db_ip: 10.0.1.20
db_password: "{{ vault_db_password }}"
db_user: dbadmin
db_name: dbadmin
server1_ip: ....
server2_ip: ....
