

USE dbadmin;

CREATE TABLE compliments
(
   compliment_id  char(2) 	        NOT NULL,
   compliment     varchar(200)       NOT NULL,

   PRIMARY KEY(compliment_id)
);


insert into compliments(compliment_id, compliment)
   values(1, 'Callers are intimidated by how funny your voicemail greeting is.');
insert into compliments
   values(2, 'You could open that jar of mayonnaise using only 3 fingers.');
