---
- name: add postgres repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
    state: present
  become: true

- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: update apt again
  command: apt-get -y update
  become: true

- name: install nginx, php and postgreSQL
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - nginx
    - postgresql-9.5
    - php5-common
    - php5-cli
    - php5-fpm
    - php5-pgsql
  tags: test

- name: starting services...
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: true
  with_items:
    - nginx
    - postgresql
    - php5-fpm

- name: copy over nginx config files
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: true
  notify: restart nginx

- name: copy over php-fpm conf files
  copy:
    src: files/www.conf
    dest: /etc/php5/fpm/pool.d/www.conf
  become: true
  notify: restart php-fpm

- name: add index.php
  template:
    src: templates/database.php
    dest: /usr/share/nginx/html/index.php
  become: true
  notify: restart nginx
