- job:
    name: check-ansible-code
    triggers:
      - reverse:
            jobs: 'githook'
            result: 'success'

    builders:
      - shell: "#!/bin/bash \n export ANSIBLE_VAULT_PASSWORD_FILE=~/.ssh/.vault_pass \n ansible-playbook --check -i /var/lib/jenkins/workspace/githook/ansible/dev /var/lib/jenkins/workspace/githook/ansible/playbook.yml --skip-tags 'test'"
