- job:
    name: deploy-dev
    triggers:
      - reverse:
            jobs: 'githook'
            result: 'success'

    builders:
    - shell: "#!/bin/bash \n export ANSIBLE_VAULT_PASSWORD_FILE=~/.ssh/.vault_pass \n ansible-playbook -i /var/lib/jenkins/workspace/githook/ansible/dev /var/lib/jenkins/workspace/githook/ansible/playbook.yml"
