---

- hosts: webservers

  roles:
    - common
    - nginx

- hosts: database

  roles:
    - role: common
    - role: postgres
    - { role: postgresql_objects, tags: test }
    - role: add_to_database

- hosts: loadbalancer

  roles:
    - { role: common, when: "env == 'prod'" }
    - { role: haproxy, when: "env == 'prod'" }
