---
postgresql_objects_users:
  - name: "{{ db_user }}"
    password: "{{ vault_password }}"
    role_attr_flags: SUPERUSER
    state: present
postgresql_objects_databases:
  - name: "{{ db_name }}"
    owner: "{{ db_user}}"
    state: present
postgresql_objects_become: true
postgresql_objects_become_user: postgres
