---
- postgresql_objects_users:
  - name: dbadmin
    password: "{{ vault_password }}"
    role_attr_flags: SUPERUSER
    state: present
- postgresql_objects_databases:
  - name: dbadmin
    owner: dbadmin
    state: present
- postgresql_objects_become: true
- postgresql_objects_become_user: postgres
